### PR TITLE
Added support for undefined option in select menu.

### PR DESCRIPTION
**Pull request by thealmightyone**

### CODE REVIEW

**Comment by thayashi** [comment]
I found 2issues (actually it's not problem of this implementation itself).
1. Even if I choose undefined, if it has default value, gohan sets the default value.
See attached files. 
screen shot 2016-10-11 at 8 54 18 pm
screen shot 2016-10-11 at 8 58 16 pm

**Comment by thayashi** [comment]
same as 1,
2. for update, if a value is already set, even I choose undefined, the resource value doesn't change.
This is obvious though, because web ui doesn't send value for the property. So far I don't know how it should send to gohan for undefined value, we need to figure it out.

**Comment by thayashi** [comment]
It looks like it needs to send as null for the property.

**Comment by stepek** [comment]
@thayashi for 1st issue. In my opinion it's a correct behavior, but ui couldn't show any other options when field have default value. 
2nd browser doesn't send undefined, but we can send null value. When i sent null i received error message.

**Comment by thayashi** [comment]
Currently the select menu shows as blank for non-select menu, but I'd like to show as "Not selected", I mean `<option>Not selected</option>` not `<option></option>`

**Comment by stepek** [comment]
Fixed

**Comment by thayashi** [comment]
For relation list, it works as expected, but for enum list, it shows always "Not selected" even if is not allowed null.

**Comment by stepek** [comment]
Fixed

**Comment by thayashi** [comment]
Thanks, but maybe my understanding is wrong, I tried schema like this:
```
      color:
        description: enum test; no defalt value
        permission:
        - create
        - update
        title: Color
        type:
        - string
        - "null"
        enum:      
        - Red
        - Green
        - Blue
```
But even I set null option to type, I got error like this:
screen shot 2016-10-28 at 1 16 19 am
Maybe It's not allowed to set null to the enum.

**Comment by thayashi** [comment]
To use null for enum, config should be like this:
```
      color:
        description: enum test; no default value
        permission:
        - create
        - update
        title: Color
        type:
        - string
        - "null"
        enum: 
        - null     
        - Red
        - Green
        - Blue
```
So for enum, condition for showing "Not selected" is type has null && enum has null.
But UI generates just string "null" from the schema, so if it is that condition, UI should remove null from the list menu.

**Comment by thayashi** [comment]
Thanks, it works, but is it possible to move this adding "Not Selected" logic to _arrayToHtml (by override)? Because as backbone form, it allows to use this type of option format:
`[{ val: 123, label: 'Text' }, { val: 123, label: 'Text' }]`
But with this commit way, it won't work.

**Comment by stepek** [comment]
Now it's works fine.

**Comment by thayashi** [comment]
Thanks, LGTM.

**Pull request merged**
