### PR TITLE
Fix problem with back button.

### PR DESCRIPTION
**Pull request by stepek**

### CODE REVIEW

**Comment by thayashi** [comment]
It looks like still it doesn't work well.
https://github.com/stepek/gohan_webui/blob/b399bfa1e01b31417a26276d6617d73907619455/app/js/routers/router.js#L69
Should it be pushState instead of replaceState?
https://github.com/stepek/gohan_webui/blob/b399bfa1e01b31417a26276d6617d73907619455/app/js/routers/router.js#L24
history.getFragment() doesn't get the current url with QueryParams. For example, even if the url is like:
http://192.168.33.10:8055/?page=2#v1.0/event_log_relations
history.getFragment() returns just v1.0/event_log_relations.
So back button doesn't work.

**Comment by stepek** [comment]
If we change ```replaceState``` to ```pushState``` we will create new history element, so i my opinion better is ```replaceState```

I tested it on my Version 53.0.2785.143
out-1

**Comment by thayashi** [comment]
Hmm, ya, there is a some sense using replaceState, if it is pushState it creates  too many history, it might cause annoying interaction. OK, let's go with replaceState so far.
One more thing, the url is forced to "#v1.0/ipam_managers" style not the "#/v1.0/ipam_managers. Is it possible to fix?

**Comment by stepek** [comment]
Fixed

**Comment by thayashi** [comment]
hmm, the back button doesn't work well, could you please check this?
https://dl.dropboxusercontent.com/u/7098/stuff/gohan_back_button.mov
If style "#/v1.0/ipam_managers" is difficult, let's consolidate as "#v1.0/ipam_managers" style.

**Comment by stepek** [comment]
All links have #/ prefix so we can stay with that.
I cannot reproduce your issue.

**Comment by thayashi** [comment]
Sorry, it looks like my env was something wrong, now it works as you said, thanks. Let me discuss one more thing,
https://dl.dropboxusercontent.com/u/7098/stuff/gohan_back_button2.mov
Like this movie,
http://192.168.33.10:8055/?page=2#/v1.0/foods
then go to:
http://192.168.33.10:8055/#/v1.0/menus
then click browser back button,
It goes to 
http://192.168.33.10:8055/#/v1.0/foods not http://192.168.33.10:8055/?page=2#/v1.0/foods
I prefer it goes to "?page=2#/v1.0/foods"
Is it possible to change like that behavior?

**Comment by stepek** [comment]
For that behavior i need change some part of routing in application.

**Comment by thayashi** [comment]
I considered my proposal situation, it might be messy to manage when remove the query parameter. The current way (remove when table view close) is simple. Let's go this way so far.
So LGTM.

**Pull request merged**
