### PR TITLE
Support multi select deletetion

### PR DESCRIPTION
**Pull request by nati**

### CODE REVIEW

**Comment by thayashi** [comment]
We are going to implement server-side paging table view, please wait until that implementation is done.

**Comment by thayashi** [comment]
If the resources are more than 5 or so, I got conflict error every time. My env is using sqlite. Can gohan server handle multiple deletion at the same time?
screen shot 2016-06-21 at 12 45 39 pm

**Comment by nati** [comment]
I think it is sqlite3 side issue.

**Comment by thayashi** [comment]
For this purpose, I think it'd be better that server side will have some api for multiple deletion, otherwise webui has to call many http requests to server. 
Also, front-end should show more detailed status like deleting animation and disabled style so that user can understand the deleting status. I can take care of front-end-side, @nati what do you think about multiple deletion api?

**Comment by nati** [comment]
I agree. It is better to support this in server side.

For deletion, what kind of deletion effect you are supposed on this? 
http://api.jquery.com/fadeout/ ?

**Comment by thayashi** [comment]
I was not thinking about deleted animation effect, more like deleting.
I was thinking like:
1. Web UI calls API
2. Each row is set 'deleting' class, it shows some deleting animation like horizon table view, and disable update oparation for the resouce
3. Once API returns the deletion status, update the view.

**Comment by nati** [comment]
@thayashi  done

I checked server side, and it looks like fixing server side takes time.
Let go with current implementation for now, and I'll fix both of client & server side later.

**Comment by thayashi** [comment]
Hmm, honestly, I' like to wait fixing server side, is this important for your project?

**Pull request closed without merging**
