### PR TITLE
Added information about required field to dialog view.

### PR DESCRIPTION
**Pull request by stepek**

### CODE REVIEW

**Comment by stepek** [comment]
gohan-webui

**Comment by thayashi** [comment]
I might want to add color to asterisk it self, to do like that, asterisk should be wrapped by span tag or something. So I think it's better to do this in template, how about it?

**Comment by stepek** [comment]
Yes in my opinion too. I will fix this.

**Comment by thayashi** [comment]
Backbone form has titleHTML, maybe using this feature is much easier than using template.

**Comment by stepek** [comment]
Version 0.14.1 backbone forms not contains titleHTML field :/  so i'll add html to title.

**Comment by thayashi** [comment]
It looks like our template issue, it should check like:
https://github.com/powmedia/backbone-forms/blob/master/src/templates/bootstrap3.js#L27
But since title can use html tag, no problem. 
LGTM.

**Pull request merged**
