### PR TITLE
UI and CSS Refactoring

### PR DESCRIPTION
**Pull request by thayashi**

### CODE REVIEW

**Comment by michal-damiecki** [comment]
In Firefox 57.0.4 (64-bit) there is some problem with select input arrow down icon. Please take a look at the screenshot.
select

**Comment by thayashi** [comment]
@michal-damiecki thanks. I checked with Mac's firefox and Windows firefox. It looks fine. You are using Ubuntu version, right? I don't have Ubuntu env, I can't check this issue...
screen shot 2018-01-17 at 5 00 44 am
screen shot 2018-01-17 at 5 01 00 am

**Comment by sealionkat** [comment]
@thayashi @michal-damiecki I have FF 56 on Ubuntu and I get the same output as in the second Toshi's screenshot. Maybe FF 57 on Ubuntu does something wrong?

**Comment by michal-damiecki** [comment]
Yes, I'm using Ubuntu (17.10). It may be caused by this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1418031

**Comment by thayashi** [comment]
@michal-damiecki ok, then let me keep as is so far regarding the select menu.

**Comment by stepek** [comment]
@thayashi @michal-damiecki @sealionkat I've checked on my env:
Centos GNOME Shell 3.22.3 and Firefox 52, 57, 58 and 59 looks good

**Pull request merged**
