### PR TITLE
Yaml widget.

### PR DESCRIPTION
**Pull request by stepek**
UIE-283

### CODE REVIEW

**Comment by michal-damiecki** [comment]
I've one concern about this widget, a user doesn't have information about the schema of this field. We can improve it in the future by adding some kind of hint. For example tooltip with information about schema or toggle button like on the image below. 

screenshot from 2018-07-10 18-39-27

**Comment by thayashi** [comment]
How initial value is defined?
Basically looks good to me. Also, @michal-damiecki you right, it's better to show some hint, maybe we can link to API docs site.
screen shot 2018-07-12 at 7 51 49 pm

**Comment by stepek** [comment]
@thayashi Regarding initial value, YAML hasn't undefined value so it's was removed in parsing to YAML. In yaml we can use only null or nill but schema don't allow send null as undefined. 
Regarding hint I can add link by uiSchema :)

**Comment by stepek** [comment]
screenshot-localhost-8080-2018 07 16-09-49-37

**Comment by thayashi** [comment]
@stepek this config data is missing in edit dialog, is it possible to show it?
Also, let's remove the help link so far. I think the schema information is enough.
bug

**Comment by stepek** [comment]
@thayashi i'll fix this issue and remove help link.

**Comment by stepek** [comment]
Fixed

**Comment by thayashi** [comment]
@stepek you removed **show schema definition** link as well? What I said was remove only the help link :)

**Comment by michal-damiecki** [comment]
LGTM

**Pull request merged**
