### PR TITLE
Changes to Tab UI for Object type

### PR DESCRIPTION
**Pull request by thayashi**
If it is object type, it changes to Tab UI. Also, removes drag &
drop UI for array, changes to simple click sort.

### CODE REVIEW

**Comment by thayashi** [comment]
I tried to change like:
`    if (this.isObjectType) {
      const $currentTab = this.$tab.children().eq(index);
}`
but I got a error in the lint, it says it never used. How do I define as const?

**Comment by thealmightyone** [comment]
Try defining const outside that "if" block.

**Comment by thayashi** [comment]
But this $currentTab is only for if (this.isObjectType) condition, if put outside if:
 `
let $currentTab = null;
if (this.isObjectType) {
  $currentTab = this.$tab.children().eq(index);
 }
`
Any other way?

**Comment by thealmightyone** [comment]
Basically if u use let/const inside that if - it will immediately go out of
scope and garbage collect your variable. Another way is to use var, but
lint might not allow that too.

**Comment by stepek** [comment]
@thayashi yes
```let let $currentTab``` out of if block.

**Comment by thayashi** [comment]
I changed the code, pls check.

**Comment by stepek** [comment]
LGTM

**Pull request merged**
