### PR TITLE
Added possibility to set sort filter.

### PR DESCRIPTION
**Pull request by stepek**
Added possibility to set sort filter by makeCollection function and by tableView constructor.

### CODE REVIEW

**Comment by thayashi** [comment]
Thanks, it works as I expected, but I realized one issue that if the key is not defined in the schema, gohan api returns 400. For example, I want to set default sort key by "name" with a custom tableview, then apply the tableview as default tableview. But some resources might not have the "name" property, gohan returns 400. So how about add check process like the given sort key is available or not? If it is not available, use id as sort key. Maybe in tableView or schemaModel.

**Comment by stepek** [comment]
I will add this feature with warning message.

**Comment by thayashi** [comment]
Cool, thanks

**Comment by thayashi** [comment]
My use case is like this, set default sort key here:
https://github.com/cloudwan/sdwan-admin-ui/blob/test-tbl-sort/app/js/views/defaultTableView.js#L9
In that case, the key check should be done in updateUrl() method in schemaModel, or in tableview at
https://github.com/stepek/gohan_webui/blob/6a5b0855b808081282dd20d529e6e33993adff00/app/js/views/tableView.js#L74
?

**Comment by stepek** [comment]
Oh i need to move check to ```updateUrl()``` method, because its only works when you create new collection.
But yes you only need to set default sort key there https://github.com/cloudwan/sdwan-admin-ui/blob/test-tbl-sort/app/js/views/defaultTableView.js#L9 and that is all you need to do.

**Comment by stepek** [comment]
I moved call method ```updateUrl()``` to ```fetch()``` method of collection.

**Comment by thayashi** [comment]
LGTM

**Pull request merged**
