### PR TITLE
Added expiration token error message.

### PR DESCRIPTION
**Pull request by stepek**

### CODE REVIEW

**Comment by thayashi** [comment]
I might want to change the message "The token is expired. Please re-login. ", Is it possible to add that option?

**Comment by stepek** [comment]
Yes, sure. in config.json will be ok?

**Comment by thayashi** [comment]
Hmm, how about put to some template??

**Comment by stepek** [comment]
If we want use error view we can't use template only for one error message. For that propose we can create some json with all error messages.

**Comment by thayashi** [comment]
OK, let's put it on config.json so far.

**Comment by stepek** [comment]
Ok thanks.

**Comment by stepek** [comment]
Done

**Comment by thayashi** [comment]
LGTM

**Pull request merged**
