### PR TITLE
Fixed nullable behavior for empty object

### PR DESCRIPTION
**Pull request by stepek**
ESI-16780

### CODE REVIEW

**Comment by thayashi** [comment]
@stepek On create case, It looks working, but for update case (delete the object when updating), it sends empty object which should be null.
null

BTW, it sends correctly as null if it is array.
screen shot 2018-01-25 at 3 35 05 pm

**Comment by stepek** [comment]
@thayashi sure, i'll fix this

**Comment by stepek** [comment]
fixed

**Comment by thayashi** [comment]
LGTM

**Pull request merged**
