### PR TITLE
Added filter action to Object and list.

### PR DESCRIPTION
**Pull request by stepek**
ESI-10459

### CODE REVIEW

**Comment by thayashi** [comment]
When schema type is object, it got error like this.
screen shot 2017-01-24 at 10 08 57 am
https://github.com/cloudwan/example_gohan_schema/blob/master/basic.yaml#L56
Also, it looks like it's not working if it is 2 nested list like this.
https://github.com/cloudwan/example_gohan_schema/blob/add-view-option/list2.yaml#L57

**Comment by thayashi** [comment]
geo

**Comment by stepek** [comment]
I added copying data from schema object to result object in filter schema method.

**Comment by thayashi** [comment]
LGTM

**Pull request merged**
