### PR TITLE
Fixed form display behavior for required property.

### PR DESCRIPTION
**Pull request by michal-damiecki**
UIE-247

* Array property:
screenshot from 2018-04-10 10-52-06

* Array property required:
screenshot from 2018-04-10 10-51-38

* Object property:
screenshot from 2018-04-10 10-52-55

* Object property required:
screenshot from 2018-04-10 10-53-29

### CODE REVIEW

**Comment by thayashi** [comment]
@michal-damiecki  Please see my comment in the ticket.

**Comment by michal-damiecki** [comment]
@thayashi Done.

**Comment by stepek** [comment]
LGTM

**Comment by thayashi** [comment]
LGTM

**Pull request merged**
