### PR TITLE
Fix problem with blinking login view on 2nd tab.

### PR DESCRIPTION
**Pull request by stepek**

### CODE REVIEW

**Comment by thayashi** [comment]
I found another problem, it fixed blinking login view, but it sometimes doesn't show actual contents.
Create new tab > copy some url ang go> it shows the content once, but it disappear > when I reload the tab, it shows.
https://dl.dropboxusercontent.com/u/7098/esi/loadbug.mov
Could you please check this issue?

**Comment by stepek** [comment]
Fixed.

**Comment by thayashi** [comment]
I can't see login page with this branch..., page is just blank. Could you please check again?

**Comment by stepek** [comment]
I added call ```render()``` method to set timeout, it's small hack because, if we want to do it better we need to refactor some part of code.

**Comment by thayashi** [comment]
If so, I don't think we need to merge this, let's keep current implementation. I think the blinking issue is a minor issue.

**Comment by stepek** [comment]
Ok so i will close this PR

**Pull request closed without merging**
